=== pete-tmbc/whitebox-navigation/data/xml/entries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:element name="jdata">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="entries"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="entries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="__comment"/>
                <xs:element ref="url"/>
                <xs:element ref="display_string"/>
                <xs:element maxOccurs="unbounded" ref="tokens"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="general"/>
                        <xs:enumeration value="business"/>
                        <xs:enumeration value="resident"/>
                        <xs:enumeration value="external"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="__comment" type="xs:string"/>
    <xs:element name="url">
        <xs:simpleType>
            <xs:restriction base="xs:anyURI">
                <xs:minLength value="12"/>
                <xs:whiteSpace value="collapse"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="display_string">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="4"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="tokens">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== pete-tmbc/whitebox-navigation/data/xml/entries.xml
<?xml version="1.0" encoding="UTF-8"?>
<jdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="entries.xsd">
    <entries type="general" id="1">
        <__comment>Google Search</__comment>
        <url>https://www.google.co.uk?</url>
        <display_string>search the internet</display_string>
        <tokens>Google</tokens>
        <tokens>find</tokens>
        <tokens>research</tokens>
    </entries>
    <entries type="general" id="2">
        <__comment>Go to Amazon</__comment>
        <url>http://www.amazon.co.uk/?</url>
        <display_string>buy books</display_string>
        <tokens>Amazon</tokens>
        <tokens>read</tokens>
        <tokens>Kindle</tokens>
    </entries>
    <entries type="general" id="3">
        <__comment>Visit Government</__comment>
        <url>http://www.gov.uk/?</url>
        <display_string>access government services</display_string>
        <tokens>UK</tokens>
        <tokens>legislation</tokens>
        <tokens>find</tokens>
        <tokens>out</tokens>
        <tokens>about</tokens>
    </entries>
</jdata>
